### ISSUE TITLE
Exception non gérée : connection échouée avec la base de données

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#122]
Lorsque la connection échoue avec la base de données, l'erreur suivante n'est pas capturée.

```
(node:423) UnhandledPromiseRejectionWarning: error: authentification par mot de passe échouée pour l'utilisateur  « ... »
    at Parser.parseErrorMessage (/opt/pdm/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/opt/pdm/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/pdm/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/opt/pdm/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Il serait mieux de renvoyer un log.
Je ferai peut-être une PR dans ce sens à la fin des modifs que j'ai commencé

**Comment by PanierAvide** [comment]
C'est changé, un message d'erreur s'affiche directement au démarrage et plus lors de l'utilisation du site.
