### ISSUE TITLE
Instabilité de node

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#150]
J'ai régulièrement l'erreur suivante qui plante node.js aléatoirement.

```
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/opt/pdm/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/opt/pdm/node_modules/express/lib/response.js:170:12)
    at res.sendFile (/opt/pdm/website/index.js:419:20)
    at /opt/pdm/node_modules/express/lib/response.js:434:22
    at onaborted (/opt/pdm/node_modules/express/lib/response.js:1027:5)
    at Immediate.<anonymous> (/opt/pdm/node_modules/express/lib/response.js:1067:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projetdumoisfr@0.0.0 start: `node --icu-data-dir=node_modules/full-icu website/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the projetdumoisfr@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osm/.npm/_logs/2021-01-14T10_25_44_471Z-debug.log
```

Peut-être est-ce lié à la gestion des exception non catchées, comme en #122 ?

**Comment by PanierAvide** [comment]
C'est possible oui, mais de souvenir ces erreurs sont assez aléatoires, il faut donc faire une revue de code plus ou moins complète pour essayer d'éviter ça.

En attendant pour la prod, tu peux faire une boucle qui relance le script s'il est en erreur :
```bash
while [ true ]; do npm run start; sleep 5; done
```

C'est pas très propre mais ça assure que le service se relance s'il se plante :sweat_smile:

**Comment by PanierAvide** [comment]
C'était peut-être pas grand chose, je viens de pousser un correctif, tu me diras si c'est suffisant ou pas :wink:

**Comment by flacombe** [comment]
Intéressant merci !

C'est déployé de mon côté, on verra bien si le soucis se représente

**Comment by flacombe** [comment]
J'ai  ce matin l'erreur suivante, je pense qu'il y a un nouveau problème

```
API started on port: 3000
m WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
_http_server.js:209
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:209:11)
    at ServerResponse.writeHead (/opt/pdm/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:200:8)
    at ServerResponse.end (/opt/pdm/node_modules/compression/index.js:103:14)
    at res.sendFile (/opt/pdm/website/index.js:419:27)
    at /opt/pdm/node_modules/express/lib/response.js:434:22
    at onaborted (/opt/pdm/node_modules/express/lib/response.js:1027:5)
    at Immediate.<anonymous> (/opt/pdm/node_modules/express/lib/response.js:1067:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projetdumoisfr@0.0.0 start: `node --icu-data-dir=node_modules/full-icu website/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projetdumoisfr@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osm/.npm/_logs/2021-01-22T08_54_52_776Z-debug.log
```

**Comment by PanierAvide** [comment]
Peut être avec ce correctif que je viens de pousser ça devrait passer ?

**Comment by flacombe** [comment]
J'ai déployé ce nouveau patch, merci nous allons voir
