### ISSUE TITLE
Erreur type 112 sur l'interface postgresql

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#197]
Hello

J'ai ce message d'erreur dans le log
```
(node:832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handl
ed with .catch(). (rejection id: 21)
WARNING: error on reading file: Error: EBADF: bad file descriptor, read 
events.js:174
      throw er; // Unhandled 'error' event
      ^

error: type 112 du message de l'interface invalide
    at Parser.parseErrorMessage (/opt/pdm/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/opt/pdm/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/pdm/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/opt/pdm/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at Client.idleListener (/opt/pdm/node_modules/pg-pool/index.js:57:10)
    at Client.emit (events.js:189:13)
    at Client._handleErrorEvent (/opt/pdm/node_modules/pg/lib/client.js:319:10)
    at Client._handleErrorMessage (/opt/pdm/node_modules/pg/lib/client.js:330:12)
    at Connection.emit (events.js:189:13)
    at parse (/opt/pdm/node_modules/pg/lib/connection.js:115:12)
    at Parser.parse (/opt/pdm/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.stream.on (/opt/pdm/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projetdumoisfr@0.0.0 start: `node --icu-data-dir=node_modules/full-icu website/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the projetdumoisfr@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osm/.npm/_logs/2021-03-15T18_21_42_724Z-debug.log
```

Visiblement une exception pgsql non catchée.

Je suis sur mon téléphone, la fibre optique qui dessert ma zone est coupée suite à la chute d'un arbre :(

**Comment by PanierAvide** [comment]
Une histoire de reconnexion et de pooling qui ne serait pas adapté ? https://stackoverflow.com/questions/9679412/can-not-close-postgresql-connection-within-node-js-script

**Comment by PanierAvide** [comment]
Je me permets de fermer le ticket si l'erreur ne s'est pas reproduite depuis, mais n'hésite pas à rouvrir si besoin :wink:

**Comment by flacombe** [comment]
C'est juste, on a du régler ça grâce à #208 peut-être, ou d'une montée en version du client pg ?
Je ne l'ai pas rencontré de nouveau
