### ISSUE TITLE
UnhandledPromise : Http 502 sur tile-vect.openstreetmap.fr

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#198]
Actuellement, tile-vect.osm.fr est en carafe, on a une `UnhandledPromise` ici : 

```
(node:18831) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://tile-vect.openstreetmap.fr/styles/liberty/style.json reason: Unexpected token < in JSON at position 0
    at /opt/pdm/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18831) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (reject
ion id: 364)
```

**Comment by PanierAvide** [comment]
Corrigé, reste à déployer
